name: Elixir CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dialyzer cache
      uses: actions/cache@v1
      env:
        cache-name: cache-dialyzer-v1
      with:
        path: priv/plts
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.4 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Make sure everything compiles
      run: mix compile
    - name: Generate docs
      run: mix docs
    - name: Run dialyzer
      run: mix dialyzer --format dialyzer
